# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/refs/tags/postgresql/16.3.5/bitnami/postgresql/values.schema.json

# https://github.com/bitnami/charts/tree/postgresql/16.3.5/bitnami/postgresql