# https://github.com/chatwork/charts/blob/master/elasticmq/values.yaml

service:
  type: ClusterIP
  port: 9324

elasticmq:
  port: 9324
  config: |
    include classpath("application.conf")
    
    node-address {
        protocol = http
        host = {{ template "elasticmq.fullname" . }}
        port = {{ .Values.elasticmq.port }}
        context-path = ""
    }
    
    rest-sqs {
        enabled = true
        bind-port = {{ .Values.elasticmq.port }}
        bind-hostname = "0.0.0.0"
        // Possible values: relaxed, strict
        sqs-limits = relaxed
    }
    
    queues {
      "logsrv.fifo" {
        fifo = true
        contentBasedDeduplication = true
      }
    }
