# https://github.com/kubernetes/ingress-nginx/blob/helm-chart-4.11.3/charts/ingress-nginx/values.yaml

controller:
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
  # extraArgs:
  #   default-ssl-certificate: "cert-manager/cert-manager-webhook-tls"
  #   enable-ssl-passthrough: "true"
