# https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-67.1.0/charts/kube-prometheus-stack

grafana:
  grafana.ini:
    auth.jwt:
      enabled: true
      username_claim: "sub"
      enable_login_token: true
      header_name: "X-JWT-Assertion"
      auto_sign_up: true
      url_login: true
      jwk_set_url: "https://devinfra.us.auth0.com/.well-known/jwks.json"
      skip_org_role_sync: true
    auth.anonymous:
      enabled: true
      org_name: "Main Org."
      org_role: "Viewer"
    security:
      allow_embedding: true
      cookie_samesite: "disabled"
    public_dashboards:
      enabled: true
  defaultDashboardsEnabled: false
  persistence:
    enabled: true
    type: "sts"
    accessModes:
      - "ReadWriteOnce"
    size: "10Gi"
    finalizers:
      - "kubernetes.io/pvc-protection"
  additionalDataSources:
    - name: mimir
      access: proxy
      orgId: 1
      version: 1
      type: prometheus
      uid: "mimir"
      url: https://{{ printf "%s-mimir-nginx.svc" .Release.Name }}:80
    - name: pulse
      access: proxy
      orgId: 1
      version: 1
      uid: "pulse"
      type: mysql
      url: https://{{ printf "%s-mysql-pulse.svc" .Release.Name }}:3306
      user: "pulse"
      secureJsonData:
        password: "pulse"
      jsonData:
        database: "pulse"
    - name: timescale
      access: proxy
      orgId: 1
      version: 1
      uid: "timescale"
      type: "postgres"
      url: https://{{ printf "%s-0.svc" .Release.Name }}:5432
      user: "tsdbadmin"
      secureJsonData:
        password: "pulse"
      jsonData:
        database: "tsdb"