# https://github.com/grafana/mimir/tree/mimir-distributed-5.6.0-weekly.321/operations/helm/charts/mimir-distributed

mimir:
  structuredConfig:
    limits:
      max_global_series_per_user: 10000000
      request_rate: 0
      request_burst_size: 0
      ingestion_rate: 1000000
      ingestion_burst_size: 100000000

    querier:
      max_concurrent: 512

    query_scheduler:
      max_outstanding_requests_per_tenant: 4096

ingester:
  persistentVolume:
    size: "100Gi"

compactor:
  persistentVolume:
    size: "100Gi"

store_gateway:
  persistentVolume:
    size: "100Gi"

alertmanager:
  enabled: false

ruler:
  enabled: false

overrides_exporter:
  enabled: false

query_scheduler:
  enabled: false

minio:
  enabled: true
