# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/refs/tags/mongodb/16.4.0/bitnami/mongodb/values.schema.json

# https://github.com/bitnami/charts/tree/mongodb/16.4.0/bitnami/mongodb
