# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/refs/tags/mysql/11.1.19/bitnami/mysql/values.schema.json

# https://github.com/bitnami/charts/tree/mysql/11.1.19/bitnami/mysql

commonAnnotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-weight": "0"
auth:
  username: "pulse"
  database: "pulse"
  password: "pulse"
  rootPassword: "pulse"
