# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/refs/tags/mysql/11.1.19/bitnami/mysql/values.schema.json

# https://github.com/bitnami/charts/tree/mysql/11.1.19/bitnami/mysql
