# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/refs/tags/postgresql/16.3.5/bitnami/postgresql/values.schema.json

# https://github.com/bitnami/charts/tree/postgresql/16.3.5/bitnami/postgresql


metrics:
  enabled: true

primary:
  persistence:
    size: "5Gi"
  initdb:
    scripts:
        init.sql: |
          CREATE TABLE vault_kv_store (
            parent_path TEXT COLLATE "C" NOT NULL,
            path        TEXT COLLATE "C",
            key         TEXT COLLATE "C",
            value       BYTEA,
            CONSTRAINT pkey PRIMARY KEY (path, key)
          );
          
          CREATE INDEX parent_path_idx ON vault_kv_store (parent_path);
          
          CREATE TABLE vault_ha_locks (
            ha_key                                      TEXT COLLATE "C" NOT NULL,
            ha_identity                                 TEXT COLLATE "C" NOT NULL,
            ha_value                                    TEXT COLLATE "C",
            valid_until                                 TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT ha_key PRIMARY KEY (ha_key)
          );


auth:
  database: "vault"
  username: "vault"
  password: "vault"

architecture: "standalone"