# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/refs/tags/redis/20.6.2/bitnami/redis/values.schema.json

# https://github.com/bitnami/charts/tree/redis/20.6.2/bitnami/redis


architecture: "standalone"

master:
  persistence:
    enabled: true
  serviceAccount:
    create: false

serviceAccount:
  create: false

auth:
  enabled: false

replica:
  replicaCount: 0