# yaml-language-server: $schema=https://raw.githubusercontent.com/hashicorp/vault-helm/refs/tags/v0.28.1/values.schema.json

# https://github.com/hashicorp/vault-helm/tree/v0.28.1

global:
  enabled: true

injector:
  enabled: false
  metrics:
    enabled: true
ui:
  enabled: true

server:
  enabled: true
  ingress:
    enabled: false
  auditStorage:
    enabled: true
  dataStorage:
    enabled: true

  # Disable vault anti-affinity that requires one pod on each node. This allows vault to run on a single node cluster.
  affinity: ""

  ha:
    enabled: true
    replicas: 3
    config: |
      disable_mlock = true
      ui = true
      
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      
      service_registration "kubernetes" {}

      storage "postgresql" {
        ha_enabled = true
        ha_table = "vault_ha_locks"

        connection_url = "postgres://vault:vault@postgres-vault-postgresql-hl:5432/vault"
      }
      
      # This is used to configure the Vault server to use AWS KMS for auto-unsealing.
      # This configuration can be found as the output if the devzero's base_cluster module when 
      # create_vault_auto_unseal_key variable is set to true. 
      # seal "awskms" {
      #   kms_key_id = "KMS_KEY_ID"
      #   region = "AWS_REGION"
      # }

ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-self-hosted"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  ingressClassName: "nginx"
  hosts:
    - host: "vault.example.com"
  tls:
    - secretName: devzero-vault-tls
      hosts:
        - "vault.example.com"