# yaml-language-server: $schema=https://raw.githubusercontent.com/hashicorp/vault-helm/refs/tags/v0.28.1/values.schema.json

# https://github.com/hashicorp/vault-helm/tree/v0.28.1

global:
  enabled: true

injector:
  enabled: false
  metrics:
    enabled: true
ui:
  enabled: true

server:
  enabled: true
  ingress:
    enabled: false
  auditStorage:
    enabled: true
  dataStorage:
    enabled: true

  # Disable vault anti-affinity that requires one pod on each node. This allows vault to run on a single node cluster.
  affinity: {}

  ha:
    enabled: true
    replicas: 3
    config: |
      disable_mlock = true
      ui = true
      
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      
      service_registration "kubernetes" {}

      storage "postgresql" {
        ha_enabled = true
        ha_table = "vault_ha_locks"

        connection_url = "postgres://vault:vault@postgres-vault-postgresql-hl:5432/vault"
      }

ingress:
  # -- Specify if the Vault Ingress is enabled
  enabled: true
  # -- Ingress Class Name. May be required for k8s >= 1.18
  ingressClassName: "nginx"
  # -- Annotations
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-self-hosted"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # -- TLS
  tls:
    - secretName: devzero-vault-tls
      hosts:
        - "vault.{{ .Values.domain }}"
  # -- Hosts
  hosts:
    - host: "vault.{{ .Values.domain }}"
      paths:
        - path: /
          pathType: Prefix