apiVersion: v1
kind: Pod
metadata:
  name: sysbox-test-server
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  runtimeClassName: sysbox-runc
  containers:
  - name: nginx-server
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "256Mi"
        cpu: "250m"