apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
handler: kata
overhead:
  podFixed:
    cpu: 250m
    memory: 130Mi
