---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kata-webhook
  name: kata-webhook
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: kata-webhook
