apiVersion: v1
kind: Secret
metadata:
  name: devzero-sa-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: devzero-sa
    kubernetes.io/service-account.namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token