{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: customer-secret-reader
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    vault:
      server: {{ .Values.devzero.vault.server }}
      path: "devzero"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "vault-csi-reader-{{.Values.devzero.teamId}}-{{.Values.devzero.region}}"
          role: customer-secret-reader
          secretRef:
            name: vault-customer-secret-reader
            namespace: {{ .Release.Namespace }}
            key: token

{{- end }}