{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: customer-secret-reader
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    vault:
      server: {{ .Values.devzero.vault.server }}
      path: "devzero"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "vault-csi-reader"
          role: customer-secret-reader
          serviceAccountRef:
            name: vault-customer-secret-reader
            namespace: {{ .Release.Namespace }}
{{- end }}