apiVersion: v1
kind: Secret
metadata:
  name: vault-customer-secret-reader
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: vault-customer-secret-reader
    kubernetes.io/service-account.namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token