apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "pulse") }}-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DEV_LAKE_ENCRYPTION_SECRET: {{ randAlpha 128 | b64enc }}
