{{- if .Values.vault.secrets.enabled | default false -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-enable-secrets-engine-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-enable-secrets-engine-role
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-enable-secrets-engine-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-enable-secrets-engine-role
subjects:
  - kind: ServiceAccount
    name: vault-enable-secrets-engine-sa
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "vault") }}-enable-secrets
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "vault") | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "devzero.podLabels" (dict "ctx" . "component" "vault") | nindent 8 }}
    spec:
      serviceAccountName: vault-enable-secrets-engine-sa
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 0
      initContainers:
        - name: check-unseal-complete
          image: bitnami/kubectl:1.30.7
          command:
            - /bin/sh
            - -c
            - |
              set -e

              while ! kubectl get job/{{ include "devzero.resourceName" (dict "ctx" . "component" "vault") }}-unseal >/dev/null 2>&1; do
                echo "Waiting for the unseal job to be created..."
                sleep 5
              done

              kubectl wait --for=condition=complete job/{{ include "devzero.resourceName" (dict "ctx" . "component" "vault") }}-unseal --timeout=600s
      containers:
        - name: vault-cli
          image: hashicorp/vault:1.17.2
          command:
            - /bin/sh
            - -c
            - |
              vault secrets list | grep -q '^{{ .Values.vault.secrets.path }}/' || vault secrets enable -path={{ .Values.vault.secrets.path }} kv-v2
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: root-token
            - name: VAULT_ADDR
              value: {{ .Values.vault.secrets.address }}
{{- end }}
