apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "hydra") }}-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ include "hydra.secret" . | indent 2 }}