FROM amazonlinux@sha256:5cb6ab1a1a13f33425b6c660a45f06298e204a22df1f9eeefe69cda3735d9757 AS build

ENV HOME=/home/root
ENV SCCACHE_CACHE_SIZE="1G"
ENV SCCACHE_DIR=$HOME/.cache/sccache

RUN dnf groupinstall -y "Development Tools"
RUN dnf install -y yum-utils rpmdevtools perl rpm-sign wget
RUN dnf builddep -y kernel

RUN wget https://github.com/mozilla/sccache/releases/download/v0.9.0/sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz && \
    tar xvf sccache-v0.9.0-x86_64-unknown-linux-musl.tar.gz && \
    mv sccache-v0.9.0-x86_64-unknown-linux-musl/sccache /usr/local/bin && \
    chmod +x /usr/local/bin/sccache && \
    rm -r sccache*

COPY linux linux
COPY configs/host linux/arch/x86/configs/dz_pvm_host_defconfig

WORKDIR linux
RUN mkdir -p "${HOME}"
RUN echo "%_binary_payload    w2T16.xzdio" >> "${HOME}/.rpmmacros" && \
    echo "%_source_payload    w2T16.xzdio" >> "${HOME}/.rpmmacros"
RUN make defconfig KBUILD_DEFCONFIG=dz_pvm_host_defconfig
RUN scripts/config -d ADDRESS_MASKING && \
    scripts/config -e DEBUG_INFO_NONE && \
    scripts/config -d DEBUG_INFO_BTF && \
    scripts/config -d DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT && \
    scripts/config -d DEBUG_INFO_DWARF4 && \
    scripts/config -d DEBUG_INFO_DWARF5 && \
    scripts/config --set-str SYSTEM_TRUSTED_KEYS ""

RUN --mount=type=cache,target=/home/root/.cache/sccache make -j$(nproc) rpm-pkg CC='sccache gcc' LOCALVERSION= EXTRAVERSION=-dz-pvm-host KBUILD_BUILD_TIMESTAMP=""

FROM scratch
COPY --from=build linux/rpmbuild/RPMS/x86_64/*.rpm .
COPY --from=build linux/rpmbuild/SRPMS/*.rpm .
