apiVersion: v2
name: dz-control-plane-deps
description: DevZero Self Hosted Control Plane CRDs
type: application
version: 0.0.1
appVersion: "v0.0.1"
home: https://docs.devzero.io/docs/self-hosted
icon: https://avatars.githubusercontent.com/u/71745520?s=400&u=10cb3d6fb9e509873fc2591ca11220573399a5de&v=4 # TODO: maybe host this image in devzero.io/static/...
dependencies:
  - name: vault
    version: 0.28.1
    repository: https://helm.releases.hashicorp.com
  - name: timescaledb-single
    version: 0.33.1
    repository: https://charts.timescale.com
    condition: timescale.enabled
  - name: elasticmq
    version: 0.2.0
    repository: https://chatwork.github.io/charts
    condition: elasticmq.enabled
  - name: docker-registry
    version: 2.2.3
    repository: https://helm.twun.io
    condition: docker-registry.enabled
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 67.1.0
    condition: backend.grafana.enabled
  - name: mimir-distributed
    version: 5.6.0-weekly.321
    repository: https://grafana.github.io/helm-charts
    condition: backend.grafana.enabled
