# secrets:
#   github_token:
#     environment: "DEBO_GITHUB_PAT"

volumes:
  polland_pycache:
  polland_mysql_data:
  polland_mysql_data_backups:
  polland_postgres_data:
  polland_postgres_data_backups:
  polland_cache:
  logsrv_postgres_data:
  logsrv_postgres_data_backups:
  mongodb_data:
  redis_data:
  hydra_postgres_data:
  hydra_postgres_data_backups:

networks:
  polland-internal:
  logsrv-internal:
  backend: 
  hydra:
  frontend:

secrets:
  github_token:
    environment: "DEBO_GITHUB_PAT"
  npm_token:
    environment: "API_CLIENT_PKG_TOKEN"

services:

  buildkitd:
    image: moby/buildkit:v0.13.0-rootless
    command:
      - --addr
      - tcp://0.0.0.0:1234
      - --oci-worker-no-process-sandbox
      - --debug
      - --config=/home/user/buildkit/buildkitd.toml
    user: "1000"
    volumes:
      - ./buildkit:/home/user/buildkit
    privileged: true
    ports:
      - 1234:1234/tcp
    networks:
      - polland-internal

  polland: &polland
    #image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/polland:self-hosted-base-2024-09-05--11-31--d94d90557be2-dirty
    image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/polland:self-hosted-base-2024-10-25--09-44--67de09ff4fb0-dirty
    command: "/wait-for-it.sh -- /start"
    container_name: polland_django
    stdin_open: true # for ipdb
    tty: true # for ipdb
    depends_on:
      - polland-mysql
      - polland-redis
      - buildkitd
#      - celeryworker
#      - flower
    volumes:
      - polland_pycache:/pycache
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
      - ./compose/local/django/start:/start
      - ./compose/local/django/start-celeryworker:/start-celeryworker
      - ./compose/local/django/start-flower:/start-flower
      - ./compose/local/django/start-celery-exporter:/start-celery-exporter
        #- $HOME/.aws/:/root/.aws/:ro
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
      - ./.envs/.local/.postgres
    environment:
      LOGSRV_DEFAULT_QUEUE: http://elasticmq:9324/queue/logsrv.fifo
      LOGSRV_DEFAULT_REGION: elasticmq
      VAULT_ENDPOINT: "http://vault:8200/"
      VAULT_AUTH_METHOD: "token"
      VAULT_TOKEN: "root"
      DOCKER_REGISTRY: "registry-server:5000"
      SELF_HOSTED: True
      ARCH: ${ARCH}
    ports:
      - 8000:8000
      - 8999:8000
    networks:
      - polland-internal
      - backend

  polland-mysql:
    image: mysql:8.2.0
    healthcheck:
      test: mysql -h backend-service-db -P 3306 --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      start_period: 10s
      interval: 2s
      timeout: 5s
      retries: 100
    container_name: polland_mysql
    volumes:
      - polland_mysql_data:/var/lib/mysql
      - polland_mysql_data_backups:/backups
    env_file:
      - ./.envs/.local/.mysql
    ports:
      - '3306:3306'
    networks:
      - polland-internal

  polland-redis:
    image: redis:6
    container_name: polland_redis
    ports:
      - "6374:6379"
    networks:
      - polland-internal

  polland-celeryworker:
    <<: *polland
    container_name: polland_celeryworker
    stdin_open: true # for ipdb
    tty: true # for ipdb
    depends_on:
      - polland-redis
      - polland-mysql
    environment:
      LOGSRV_DEFAULT_QUEUE: http://elasticmq:9324/queue/logsrv.fifo
      LOGSRV_DEFAULT_REGION: elasticmq
      VAULT_ENDPOINT: "http://vault:8200/"
      VAULT_AUTH_METHOD: "token"
      VAULT_TOKEN: "root"
      DOCKER_REGISTRY: "registry-server:5000"
      SELF_HOSTED: True
      ARCH: ${ARCH}
    ports: []
    command: /start-celeryworker
    networks:
      - polland-internal

  polland-celerybeat:
    <<: *polland
    container_name: polland_celerybeat
    depends_on:
      - polland-redis
      - polland-mysql
    ports: []
    command: /start-celerybeat
    networks:
      - polland-internal

  polland-flower:
    <<: *polland
    container_name: polland_flower
    depends_on: []
    ports:
      - 5555:5555
      - 8998:5555
    command: /start-flower
    networks:
      - polland-internal

  mongodb:
    image: mongo:6.0
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb:27017/test --quiet"
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 10s
      start_interval: 5s
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  backend-redis:
    image: redis:7.2
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  backend-asynqmon: # for monitoring backend jobs
    image: hibiken/asynqmon
    platform: linux/amd64
    restart: always
    ports:
      - 9990:9990
    networks:
      - backend
    command: "--port 9990 --redis-addr=backend-redis:6379"

  backend:
    #image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/backend:self-hosted-base-2024-09-13--14-18--959638a6b270-dirty
    image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/backend:self-hosted-base-2024-10-25--13-07--67de09ff4fb0-dirty
    container_name: backend
    depends_on:
      backend-redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      ARCH: ${ARCH}
      CONFIG_FILENAME: development
      ENVIRONMENT: development
      INFLUXDB_URL: http://influxdb:8086
      LOGSRV_DEFAULT_QUEUE: http://elasticmq:9324/queue/logsrv.fifo
      LOGSRV_DEFAULT_REGION: elasticmq
      POLLAND_URL: http://polland:8000/
      MONGODB_URL: mongodb://mongodb:27017
      REDIS_URL: redis://backend-redis:6379
      DEFAULT_DZ_BASE_IMAGE_TAG: ${DEVBOX_IMAGE_TAG}
      CONTROL_PLANE_URL: http://host.lima.internal:8831
      HYDRA_URL: https://hydra.selfzero.net:8181
      HYDRA_API_KEY: ${HYDRA_API_KEY}
      LICENSE_KEY: ${LICENSE_KEY}
      SELF_HOSTED: true
      JWT_PRIVATE_KEY: ${PRIVATE_KEY}
      DOCKER_REGISTRY: registry-server:5000/devzero-devbox-base
    ports:
      - 8444:8444
    networks:
      - backend

  buildqd:
    #image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/buildqd:self-hosted-base-2024-09-05--09-00--b3f4b47bdd67-dirty
    image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/buildqd:self-hosted-base-2024-10-25--09-26--67de09ff4fb0-dirty
    container_name: buildqd
    environment:
      BACKEND_ADDRESS: http://backend:8444/internal/
      REDIS_ADDRESS: polland-redis:6379
      POLLAND_ADDRESS: http://polland:8000
      BUILDKIT_ADDRESS: buildkitd:1234 
      LOGSRV_DEFAULT_QUEUE: http://elasticmq:9324/queue/logsrv.fifo
      LOGSRV_DEFAULT_REGION: elasticmq
      SELF_HOSTED: true
    depends_on:
      - polland 
    networks:
      - polland-internal
      - backend

  logsrv-postgres:
    image: postgres:16.3
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "logsrv", "-U", "MkHqCahbCImFqRlnGoqIZPsvddlWHSbh"]
      start_period: 10s
      interval: 2s
      timeout: 5s
      retries: 100
    container_name: logsrv_postgres
    volumes:
      - logsrv_postgres_data:/var/lib/postgresql/data/
      - logsrv_postgres_data_backups:/backups
    environment:
      POSTGRES_HOST: logsrv-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: logsrv 
      POSTGRES_USER: MkHqCahbCImFqRlnGoqIZPsvddlWHSbh
      POSTGRES_PASSWORD: pe6hYO141rRuxE3ePpjTRsDE3AohQeTyoamhNo4iCN5TeGlwdu0snTnsIF7OUVsQ
    networks:
      - logsrv-internal

  logsrv:
    #image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/logsrv:self-hosted-base-2024-09-05--08-57--b3f4b47bdd67-dirty
    image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/logsrv:self-hosted-base-2024-10-25--09-33--67de09ff4fb0-dirty
    container_name: logsrv
    depends_on:
      - logsrv-postgres
    environment:
      CONFIG_FILENAME: preproduction 
      SERVICE_PORT: 8442
      SELF_HOSTED: true
      QUEUE_URL: "http://elasticmq:9324/queue/logsrv.fifo"
      PGPASSWORD: "pe6hYO141rRuxE3ePpjTRsDE3AohQeTyoamhNo4iCN5TeGlwdu0snTnsIF7OUVsQ"
      POSTGRES_URL: "postgresql://MkHqCahbCImFqRlnGoqIZPsvddlWHSbh@logsrv-postgres:5432/logsrv"
      USE_FAKE_DB: false 
      USE_FAKE_QUEUE: false 
      USE_FAKE_AUTH_MIDDLEWARE: false 
      VAULTED_AUTH_PUBLIC_KEY: ${PUBLIC_KEY}
    ports:
      - 8442:8442
    networks:
      - frontend
      - logsrv-internal

  api-gateway:
    #image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/api-gateway:self-hosted-base-2024-09-05--08-49--b3f4b47bdd67-dirty
    image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/api-gateway:self-hosted-base-2024-10-25--09-37--67de09ff4fb0-dirty
    container_name: api-gateway
    environment:
      ENVIRONMENT: development
      LISTENER_ENDPOINT: 0.0.0.0:8445
      BACKEND_URL: http://backend:8444
      VAULTED_AUTH_PUBLIC_KEY: ${PUBLIC_KEY}
    ports:
      - 8445:8445
      - 8831:8445
    networks:
      - backend
      - frontend

  devzero-website:
    #image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/devzero-website:self-hosted-base-2024-09-05--10-25--ea407c8248bd-dirty
    image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/devzero-website:self-hosted-base-2024-10-25--12-33--34c7498a4146-dirty
    container_name: devzero-website
    environment:
      NEXT_AUTH_JWT_SIGNING_PRIV_KEY: ${PRIVATE_KEY}
      API_BASE_URL: "http://api-gateway:8445/api/v0"
      API_BASE_URL_V2: "http://api-gateway:8445/backend/v0"
      AUTH0_BASE_URL: "https://www.devzero.io"
      NEXT_PUBLIC_BYPASS_AUTH0_FLOW: "true"
      NEXTAUTH_SECRET: "testingindev"
    ports:
      - 3000:3000
    networks:
      - frontend


  hydra-db:
    image: postgres
    restart: always
    ports:
      - "5564:5432"
    environment:
      POSTGRES_PASSWORD: hydra 
      POSTGRES_DB: hydra
      POSTGRES_USER: hydra
    volumes:
      - hydra_postgres_data:/var/lib/postgresql/data/
      - hydra_postgres_data_backups:/backups
    networks:
      - hydra

  hydra:
    #image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/hydra:self-hosted-base-2024-09-05--09-25--1e367a8a8682-dirty
    image: 056855531191.dkr.ecr.us-west-2.amazonaws.com/hydra:self-hosted-base-2024-10-25--10-05--d59b0806d5b4
    container_name: hydra
    ports:
      - "8181:8181"
      - "3478:3478"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://hydra.selfzero.net:8181/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      - hydra-db
    environment:
      - HEADSCALE_SERVER_URL=https://hydra.selfzero.net:8181
      - HEADSCALE_LISTEN_ADDR=0.0.0.0:8181
      - HEADSCALE_DATABASE_TYPE=postgres
      - HEADSCALE_DATABASE_POSTGRES_SSL=true
      - HEADSCALE_DATABASE_POSTGRES_HOST=hydra-db
      - HEADSCALE_DATABASE_POSTGRES_PORT=5432
      - HEADSCALE_DATABASE_POSTGRES_NAME=hydra
      - HEADSCALE_DATABASE_POSTGRES_USER=hydra
      - HEADSCALE_DATABASE_POSTGRES_PASS=hydra
      - HEADSCALE_DATABASE_REDIS_URL=redis://default:@redis:6379/0
      - HEADSCALE_CONFIG=/etc/headscale/development.yaml
      - HEADSCALE_DERP_SERVER_ENABLED=true
      - HEADSCALE_DERP_SERVER_AUTOMATICALLY_ADD_EMBEDDED_DERP_REGION=true
      - HEADSCALE_DERP_URLS=""
      - HEADSCALE_TLS_CERT_PATH=/etc/ssl/certs/fullchain.pem
      - HEADSCALE_TLS_KEY_PATH=/etc/ssl/private/privkey.pem
    volumes:
      - ./hydra/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./hydra/privkey.pem:/etc/ssl/private/privkey.pem
    networks:
      backend:
        aliases: 
          - hydra.selfzero.net
      hydra:

  vault:
    image: vault:1.13.3
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: /bin/sh -c "vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=root & /vault/config/init.sh && wait"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - polland-internal

  registry-server:
    image: registry:2.8.2  # Using a specific version of the registry
    restart: always
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'  # Enabling deletion of images
    volumes:
      - ./registry/data:/var/lib/registry  # Persistent data storage
    ports:
      - 5959:5000
    networks:
      - polland-internal
      - backend

  registry-ui:
    image: joxit/docker-registry-ui:main  # Using the latest main branch build
    container_name: registry-ui
    restart: always
    ports:
      - 9997:80  # Exposing UI on port 9997
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000  # Link to the registry server
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    networks:
      - polland-internal

  elasticmq:
    image: softwaremill/elasticmq
    volumes:
      - ./elasticmq/custom.conf:/opt/elasticmq.conf
    ports:
      - 9324:9324
      - 9325:9325  # Optional, for the web UI
    networks:
      - polland-internal
      - backend
      - logsrv-internal
