apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "buildqd") }}
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "buildqd") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  serviceName: "buildqd"
  replicas: {{ .Values.buildqd.replicas }}
  selector:
    matchLabels:
      {{- include "devzero.selectorLabels" (dict "ctx" . "component" "buildqd") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devzero.selectorLabels" (dict "ctx" . "component" "buildqd") | nindent 8 }}
      annotations:
        {{- include "devzero.podAnnotations" (dict "ctx" . "component" "buildqd") | nindent 8 }}
    spec:
      containers:
        - name: buildqd
          image: "{{ .Values.image.repository }}/{{ .Values.buildqd.imageName }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.buildqd.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.buildqd.service.metricsPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.buildqd.resources | nindent 12 }}
          volumeMounts:
            - name: buildqd-config
              mountPath: /config/self_hosted.yaml
              subPath: self_hosted.yaml
            - name: buildkit-state
              mountPath: /var/lib/buildkit
          env:
            - name: CONFIG_FILENAME
              value: "self_hosted"
        - name: buildkitd
          securityContext:
            {{- toYaml .Values.buildqd.buildkit.securityContext | nindent 12 }}
          image: "{{ .Values.buildqd.buildkit.image.repository }}:{{ .Values.buildqd.buildkit.image.tag }}"
          imagePullPolicy: {{ .Values.buildqd.buildkit.image.pullPolicy }}
          command:
            - {{ .Values.buildqd.buildkit.command }}
          {{- with .Values.buildqd.buildkit.args }}
          args:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: buildkit
              containerPort: 1234
              protocol: TCP
          volumeMounts:
            - name: buildkit-config
              mountPath: /etc/buildkit/buildkitd.toml
              subPath: buildkitd.toml
            - name: buildkit-state
              mountPath: /var/lib/buildkit
          resources:
            {{- toYaml .Values.buildqd.buildkit.resources | nindent 12 }}
      volumes:
        - name: buildqd-config
          configMap:
            name: {{ include "devzero.resourceName" (dict "ctx" . "component" "buildqd") }}
        - name: buildkit-config
          configMap:
            name: {{ include "devzero.resourceName" (dict "ctx" . "component" "buildqd") }}-buildkit
      {{- with .Values.buildqd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.buildqd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.buildqd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: buildkit-state
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.buildqd.buildkit.persistentVolumeClaim.storageSize }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
