{{- $svcPort := .Values.gateway.service.port -}}
{{- $svcName := include "devzero.resourceName" (dict "ctx" . "component" "gateway") }}
{{- if .Values.gateway.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "gateway") }}
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "gateway") | nindent 4 }}
  annotations:
  {{- with .Values.gateway.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if .Values.gateway.ingress.ingressClassName }}
  ingressClassName: {{ .Values.gateway.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.gateway.ingress.tls }}
  tls:
    {{- range .Values.gateway.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      secretName: {{ tpl .secretName $ | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
        {{- end }}
    {{- end}}
{{- end }}
