apiVersion: v2
name: dz-control-plane-crds
description: DevZero Self Hosted Control Plane CRDs
type: application
version: 0.0.1
appVersion: "v0.0.1"
home: https://docs.devzero.io/docs/self-hosted
icon: https://avatars.githubusercontent.com/u/71745520?s=400&u=10cb3d6fb9e509873fc2591ca11220573399a5de&v=4 # TODO: maybe host this image in devzero.io/static/...
dependencies:
  - name: cert-manager 
    version: v1.10.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: ingress-nginx
    version: 4.4.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
