devzero:
  teamId: ""
  region: ""
  vault:
    server: "https://csi.devzero.io"

nodeLabeler:
  enabled: true

## @section Credentials Configuration
credentials:
  ## @param credentials.registry Container registry URL
  registry: ""
  ## @param credentials.username Registry username
  username: ""
  ## @param credentials.password Registry password
  password: ""
  ## @param credentials.email Registry email address
  email: ""
