## @section Devzero
devzero:
  ## @param devzero.teamId Team identifier. Only needed for SaaS self-hosted data plane
  teamId: ""
  ## @param devzero.region Base Region
  region: ""
  ## @section Vault
  vault:
    ## @param devzero.vault.server Vault server
    server: "https://vault.example.com"

## @section Node Labeler
nodeLabeler:
  ## @param nodeLabeler.enabled Is node labeler enabled
  enabled: true

## @section Credentials Configuration
credentials:
  ## @param credentials.enable Enable docker hub credentials
  enable: true
  ## @param credentials.registry Container registry URL
  registry: ""
  ## @param credentials.username Registry username
  username: ""
  ## @param credentials.password Registry password
  password: ""
  ## @param credentials.email Registry email address
  email: ""
