apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "web") }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  next-auth-secret: {{ .Values.web.nextAuthSecret | quote }}