apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "web") }}
  labels:
    {{- include "devzero.labels" (dict "ctx" . "component" "web") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  API_BASE_URL: "http://{{ include "devzero.resourceName" (dict "ctx" . "component" "gateway")}}:{{ .Values.gateway.service.port}}/api/v0"
  API_BASE_URL_V2: "http://{{ include "devzero.resourceName" (dict "ctx" . "component" "gateway")}}:{{ .Values.gateway.service.port}}/backend/v0"
  NEXT_PUBLIC_API_LOGS_URL: "http://{{ include "devzero.resourceName" (dict "ctx" . "component" "logsrv")}}:{{ .Values.logsrv.service.port}}"
  NEXT_PUBLIC_GRAFANA_URL: "https://grafana.{{ .Values.domain }}"
  NEXT_PUBLIC_HYDRA_URL: "http://{{ include "devzero.resourceName" (dict "ctx" . "component" "hydra")}}:{{ .Values.hydra.service.port}}"
  AUTH0_BASE_URL: "https://{{ .Values.domain }}"
  {{- $ctx := . -}}
  {{- range $key, $val := index .Values.web.env }}
  {{ $key }}: {{ tpl $val $ctx | quote }}
  {{- end}}
