apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devzero.resourceName" (dict "ctx" . "component" "web") }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  next-auth-secret: {{- if .Values.web.nextAuthSecret }}
    {{ .Values.web.nextAuthSecret | b64enc | quote }}
  {{- else }}
    {{- $secretName := include "devzero.resourceName" (dict "ctx" . "component" "web") }}
    {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
    {{- if $existing }}
      {{ index $existing.data "next-auth-secret" | quote }}
    {{- else }}
      {{ randAlphaNum 32 | printf "%s" | b64enc | quote }}
    {{- end }}
  {{- end }}