name: Build Kata AMI

on:
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<ROLE_NAME> # Replace with your AWS role ARN
          aws-region: us-west-1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y packer

      - name: Run Build AMI Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Pass GitHub Token securely
        run: |
          chmod +x ./kata/packer/build-ami.sh
          ./kata/packer/build-ami.sh
