name: Clean GCP Unused Disks

on:
  push:
    branches:
      - garvit/clean-gcp-disks
  schedule:
    - cron: '0 7 * * *'  # Runs daily at midnight Pacific Time (7:00 UTC)
  workflow_dispatch: 

jobs:
  clean-disks:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/926977153451/locations/global/workloadIdentityPools/dsh-testing-pool-id/providers/github-actions-pool'
          service_account: 'devzero-self-hosted@devzero-self-hosted.iam.gserviceaccount.com'
          create_credentials_file: true
          export_environment_variables: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: List and delete unused disks
        run: |
          echo "Scanning for unused disks across all zones..."
          zones=$(gcloud compute zones list --format="value(name)")
          total_zones=$(echo "$zones" | wc -l)
          current_zone=0
          total_unused=0
          zones_with_disks=""
          
          for zone in $zones; do
            ((current_zone++))
            # Use carriage return to update the same line
            printf "\rProcessing zone %d/%d: %s" $current_zone $total_zones $zone
            
            unused_disks=$(gcloud compute disks list \
              --filter="zone:$zone AND (users=null OR NOT users:*)" \
              --format="value(name)" 2>/dev/null)
            
            if [ -n "$unused_disks" ]; then
              count=$(echo "$unused_disks" | wc -l)
              total_unused=$((total_unused + count))
              zones_with_disks="${zones_with_disks}${zone} (${count} disks), "
              
              # Print on a new line when disks are found
              echo -e "\nFound $count unused disk(s) in $zone"
              for disk in $unused_disks; do
                echo "→ Deleting disk: ${disk}"
                gcloud compute disks delete "$disk" \
                  --zone="$zone" \
                  --quiet >/dev/null 2>&1
              done
            fi
          done
          
          # Print final summary
          echo -e "\n-------------------------------------------"
          echo "Scan Complete!"
          if [ $total_unused -eq 0 ]; then
            echo "Status: No unused disks found in any zone"
          else
            echo "Status: Deleted $total_unused unused disk(s)"
            echo "Affected zones: ${zones_with_disks%,*}"
          fi
          echo "Total zones scanned: $total_zones"
          echo "-------------------------------------------"