name: demo-workflow
on:
  workflow_dispatch:
jobs:
  demo:
    name: Run me!
    runs-on: devzero-ubuntu-24.04
    strategy:
      matrix:
        name: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: Hello world
        run: echo "Hello world"
      - name: Sleep Number {{ matrix.name }}
        run: sleep 20
