name: Deploy DevZero Control Plane

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  apply:
    name: Apply Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7 # Specify the required version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::484907513542:role/github-actions-oidc-role
          aws-region: us-west-1
      
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      - name: Run Apply Stage
        run: |
          chmod +x ./terraform/dsh-testing.sh
          DOMAIN_NAME="${{ secrets.DOMAIN_NAME }}"
          EMAIL="${{ secrets.EMAIL }}"
          TF_BACKEND="S3"
          BUCKET_NAME="${{ secrets.BUCKET_NAME }}"
          ./terraform/dsh-testing.sh apply_terraform

  eks-setup:
    name: EKS Setup
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3 # Ensure Terraform is available here as well
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::484907513542:role/github-actions-oidc-role
          aws-region: us-west-1

      - name: Run EKS Setup Stage
        run: |
          chmod +x ./terraform/dsh-testing.sh
          ./terraform/dsh-testing.sh get_eks_info
          ./terraform/dsh-testing.sh configure_kubeconfig
          ./terraform/dsh-testing.sh login_to_helm_registry
          ./terraform/dsh-testing.sh install_devzero_crds
          ./terraform/dsh-testing.sh install_devzero_control_plane
          ./terraform/dsh-testing.sh get_ingress_service

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    needs: eks-setup
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7 # Add Terraform setup here as well

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::484907513542:role/github-actions-oidc-role
          aws-region: us-west-1

      - name: Run Destroy Stage
        run: |
          chmod +x ./terraform/dsh-testing.sh
          ./terraform/dsh-testing.sh cleanup
