name: Test sz Control Plane on AWS EKS

on:
  # push:
  #   branches:
  #     - garvit/pipeline-testing
  workflow_dispatch:

jobs:
  setup:
    name: Setup & Clone Repository
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::484907513542:role/github-actions-oidc-role
          aws-region: us-west-1
          
      - name: Clone DevZero Self-Hosted Repository
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://$GH_PAT@github.com/devzero-inc/self-hosted.git -b garvit/pipeline-testing

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Apply Terraform (Base Cluster)
        run: |
          cd self-hosted/terraform/examples/aws/base-cluster
          terraform init
          terraform apply -auto-approve
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
          echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_ENV
          echo "PUBLIC_SUBNET_IDS=$(terraform output -json public_subnet_ids | jq -c .)" >> $GITHUB_ENV
          echo "PRIVATE_SUBNET_IDS=$(terraform output -json private_subnet_ids | jq -c .)" >> $GITHUB_ENV

  cluster-extensions-kube-config:
    name: Deploy Cluster Extensions & Configure Kubeconfig
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Update Cluster-Extensions tfvars
        run: |
          cat <<EOT > self-hosted/terraform/examples/aws/cluster-extensions/terraform.tfvars
          region = "us-west-1"
          vpc_id = "$VPC_ID"
          public_subnet_ids = $PUBLIC_SUBNET_IDS
          private_subnet_ids = $PRIVATE_SUBNET_IDS
          enable_cluster_autoscaler = false
          cluster_name = "$CLUSTER_NAME"
          EOT

      - name: Deploy Cluster Extensions
        run: |
          cd self-hosted/terraform/examples/aws/cluster-extensions
          terraform init
          terraform apply -auto-approve

      - name: Configure Kubernetes cluster Access
        run: |
          aws eks update-kubeconfig --region us-west-1 --name $CLUSTER_NAME

  deploy-control-plane:
    name: Deploy Control Plane
    runs-on: ubuntu-latest
    needs: cluster-extensions-kube-config
    steps:
      - name: Deploy Control Plane Dependencies
        run: |
          aws eks update-kubeconfig --region us-west-1 --name $CLUSTER_NAME
          cd self-hosted/charts/dz-control-plane-deps
          make install

      - name: Install yq 
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Update values.yaml for Control Plane
        run: |
          yq e -i '
            .credentials.username = "${{ secrets.DOCKERHUB_USERNAME }}" |
            .credentials.password = "${{ secrets.DOCKERHUB_TOKEN }}" |
            .credentials.email = "garvit@devzero.io" |
            .backend.licenseKey = "${{ secrets.BACKEND_LICENSE_KEY }}"
          ' self-hosted/charts/dz-control-plane/values.yaml

      - name: Deploy DevZero Control Plane
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          cd self-hosted/charts/dz-control-plane
          make add-docker-creds
          make install

  deploy-data-plane:
    name: Deploy Data Plane
    runs-on: ubuntu-latest
    needs: deploy-control-plane
    steps:
      - name: Deploy Data Plane Dependencies
        run: |
          cd self-hosted/charts/dz-data-plane-deps
          make install

      - name: Update values.yaml for Data Plane
        run: |
          cat <<EOT > self-hosted/charts/dz-control-plane/values.yaml
          devzero:
            teamId: ""
            region: "us-west-1"
            vault:
              server: "https://csi.devzero.io"
          nodeLabeler:
            enabled: true
          credentials:
            registry: "docker.io"
            username: "${{ secrets.DOCKERHUB_USERNAME }}"
            password: "${{ secrets.DOCKERHUB_TOKEN }}"
            email: "garvit@devzero.io"
          EOT

      - name: Deploy DevZero Data Plane
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          cd self-hosted/charts/dz-control-plane
          make install

  validate-deployment:
    name: Validate Deployment
    runs-on: ubuntu-latest
    needs: deploy-data-plane
    steps:
      - name: Check Control Plane Pods
        run: |
          kubectl get pods -n devzero

      - name: Check Data Plane Pods
        run: |
          kubectl get pods -n devzero-self-hosted

      - name: Check Ingress
        run: |
          kubectl get ingress -n devzero-self-hosted

  # cleanup:
  #   name: Cleanup Infrastructure
  #   runs-on: ubuntu-latest
  #   needs: validate-deployment
  #   if: always()
  #   steps:
  #     - name: Destroy Cluster Extensions
  #       run: |
  #         cd self-hosted/terraform/examples/aws/cluster-extensions
  #         terraform destroy -auto-approve

  #     - name: Destroy AWS Dependencies
  #       run: |
  # <        aws ec2 delete-internet-gateway --internet-gateway-id $(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$VPC_ID" --query 'InternetGateways[0].InternetGatewayId' --output text) || true
  #         aws ec2 delete-nat-gateway --nat-gateway-id $(aws ec2 describe-nat-gateways --filter "Name=vpc-id,Values=$VPC_ID" --query 'NatGateways[0].NatGatewayId' --output text) || true
  #         aws ec2 delete-route-table --route-table-id $(aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$VPC_ID" --query 'RouteTables[?Associations[0].Main!=`true`].RouteTableId' --output text) || true
  #         for subnet in $(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query 'Subnets[*].SubnetId' --output text); do
  #           aws ec2 delete-subnet --subnet-id $subnet || true
  #         done
  #         for sg in $(aws ec2 describe-security-groups --filters "Name=vpc-id,Values=$VPC_ID" --query 'SecurityGroups[?GroupName!=`default`].GroupId' --output text); do
  #           aws ec2 delete-security-group --group-id $sg || true
  #         done
  #     - name: Destroy Base Cluster
  #       run: |
  #         cd self-hosted/terraform/examples/aws/base-cluster
  #         terraform destroy -auto-approve