name: Push Services Image

on:
  push:
    branches:
      - garvit/pipeline-testing
  workflow_dispatch:

jobs:
  build-and-push-docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clone DevZero Services Repository
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://$GH_PAT@github.com/devzero-inc/services.git

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Images
        env:
          SERVICES: "polland backend api-gateway hydra falco cortex logsrv buildqd"
          DOCKERHUB_USER: "${{ secrets.DOCKERHUB_USERNAME }}"
        run: |
          ls
          for service in $SERVICES; do

            ls services/$service

            if [ -f "services/$service/Dockerfile" ]; then
              echo "Building and pushing image for $service..."

              IMAGE_NAME="devzeroinc/$service"
              IMAGE_TAG="$(git rev-parse --short HEAD)"

              docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_TAG -f services/$service/Dockerfile services/$service
              docker push $IMAGE_NAME:latest
              docker push $IMAGE_NAME:$IMAGE_TAG
            else
              echo "Skipping $service - No Dockerfile found"
            fi
          done
